# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  push:
    paths:
      - 'another/**'

env:
  BASEDIR: another

jobs:
  get-list:
    name: get list
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: test code
        run: |
          ls
          content=$(`ls ${{ env.BASEDIR }}`)
