# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  push:
    branches:
      - master

jobs:
  update-destination:
    name: Create pull request to update destination
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Make archive destination directory
        run: mkdir -vp ~/www/archive

      - name: Move output to destination directory
        run: mv input/test.json ~/www/archive/
      
      - name: Checkout vik-m/push-destination
        uses: actions/checkout@v2
        with:
          repository: vik-m/push-destination
          token: ${{ secrets.API_GITHUB_TOKEN }}
          ref: ${{ github.repository }}

      - name: Copy built site files into Git branch
        run: cp ~/www/archive/test.json ./output/

      - name: Log
        run: echo ${{ toJson(github) }}

      - name: Store number of changes
        run: echo '::set-output name=count::$(git status --untracked-files=no --porcelain | wc -l)'
        id: log_changes

      - name: Add changes to git tracking and commit changes
        if: steps.log_changes.outputs.count > 0
        run: |
          git config --local user.name 'Vikram Malhotra'
          git config --local user.email 'vikram.malhotra@x-factory.jp'
          git add -A .
          git commit -v -m 'Updated output for ${{ github.repository }}'

      - name: Push changes
        if: steps.log_changes.outputs.count > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_GITHUB_TOKEN }}
          branch: ${{ github.repository }}
          repository: vik-m/push-destination
