# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  push:
    branches:
      - master

jobs:
  update-destination:
    name: Create pull request to update destination
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout vik-m/push-destination
        uses: actions/checkout@v2
        with:
          repository: vik-m/push-destination
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: List current folder
        run: ls -R .

      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: temp-location

      - name: List current folder
        run: ls -R .

      # - name: Commit changes
      #   run: |
      #     git config user.name 'Vikram Malhotra'
      #     git config user.email 'vikram.malhotra@x-factory.jp'
      #     git add -A
      #     git commit -m 'Updated swagger specs for ${{ github.repository }}'

      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.API_GITHUB_TOKEN }}
      #     commit-message: 'Updated swagger specs for ${{ github.repository }}'
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     branch: ${{ github.repository }}-${{ github.ref }}
      #     title: 'Updated swagger specs for ${{ github.repository }}'
      #     body: |
      #       ## Tasks
      #       - [ ] Updated swagger specs for ${{ github.repository }}
      #     reviewers: vik-m
      #     draft: false
