# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# Execute workflow on push (develop/master) or pull request to any branch
on:
  push:
    branches:
      - master

jobs:
  update-destination:
    name: Create pull request to update destination
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Make archive destination directory
        run: mkdir -vp ~/www/archive

      - name: Move output to destination directory
        run: mv input/test.json ~/www/archive/
      
      - name: Checkout vik-m/push-destination
        uses: actions/checkout@v2
        with:
          repository: vik-m/push-destination
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Copy built site files into Git branch
        run: cp ~/www/archive/test.json ./output/

      - name: Add changes to git tracking
        run: git add -A .

      - name: Commit changes
        run: |
          git config --local user.name 'Vikram Malhotra'
          git config --local user.email 'vikram.malhotra@x-factory.jp'
          git commit -m 'Updated output for ${{ github.repository }}'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_GITHUB_TOKEN }}
          branch: updated-source

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.1.9
        with:
          verbose: true
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: updated-source
          base: master
          title: 'Updated swagger specs for ${{ github.repository }}'
          body: |
            ## Tasks
            - [ ] Updated swagger specs for ${{ github.repository }}
